### PR TITLE
Feature: Allow nested submenus

### LINKED ISSUE #90: Can we have sub-submenus?
Is it possible to have a sub-submenu? Below is a markup example:

``` html
  <nav class="pushy pushy-right">
    <ul>
      <li class="pushy-link">
        <a href="#">Item 1</a>
      </li>
      <li class="pushy-submenu">
        <a href="#">Item 2 &gt;</a>
        <ul>
          <li class="pushy-link"><a href="#">sub item 1</a></li>
          <li class="pushy-submenu">
            <a href="#">sub item 2 &gt;</a>
            <ul>
              <li class="pushy-link"><a href="#">sub sub item 1</a></li>
              <li class="pushy-link"><a href="#">sub sub item 2</a></li>
              <li class="pushy-link"><a href="#">sub sub item 3</a></li>
            </ul>
          </li>
          <li class="pushy-link"><a href="#">sub item 2</a></li>
        </ul>
      </li>
      <li class="pushy-link">
        <a href="#">Item 3</a>
      </li>
    </ul>
  </nav>
```

It wasn't clear to me if this only supported one level of submenus, or if I could have a nested submenu within a submenu.

Thanks!

### PR DESCRIPTION
**Pull request by gerardo-rodriguez**
This PR updates pushy to allow nested submenus.

Updates include:
- Add check for nested submenus
- Stop propagation to help manage nested submenus
- Add `preventDefault()` to allow submenu open/close links to function only as such
- Add [`main` entry](https://docs.npmjs.com/files/package.json#main) to `package.json` to allow install via `npm install github:mygithubuser/myproject`

Closes #90

### CODE REVIEW

**Comment by christophery** [comment]
Thanks for submitting this PR! I took it for a quick spin and noticed a couple of things:

1. There needed to be a couple of minor CSS changes to hide the nested submenus on initial menu open.

Before: 
screen shot 2016-05-31 at 8 49 32 pm

After: 
screen shot 2016-05-31 at 8 50 26 pm

Pretty easy to fix, I just added ```>``` to the **UL** and submenu icon classes:

```
.pushy-submenu-closed{
    > ul{
        max-height: 0;
        overflow: hidden;
    }

    .pushy-link{
        opacity: 0;
    }
}

.pushy-submenu-open{
    > ul{
        max-height: 1000px;
    }

    .pushy-link{
        opacity: 1;
    }
    
    /* Submenu Icon */

    > a::after {
        -webkit-transform: translateY(-50%) rotate(90deg);
        -ms-transform: translateY(-50%) rotate(90deg);
        transform: translateY(-50%) rotate(90deg);
    }
}
```

2.  If you close a nested submenu by clicking on itself, it appears to be closing the parent submenu as well (I seems odd behavior?), It totally works fine if you are just closing the opened nested submenus by opening a closed submenu (which closes any opened nested submenus).

Attached is an animated gif to illustrate what I'm talking about:

nested-submenus

3. It doesn't appear that the submenu fallback (IE 9) has support for nested submenus.

**Comment by Internapse** [comment]
For multiple submenus, I had to comment out the first e.preventDefault(); which comes after  e.stopPropagation(); for the links to continue working.

**Comment by michaeltlombardi** [comment]
This is the only feature currently keeping us from implementing pushy - is there anything blocking this from being included?

**Comment by christophery** [comment]
@michaeltlombardi [Yes, see my comments/issues with this PR](https://github.com/christophery/pushy/pull/96#issuecomment-222865167).

**Comment by MichaelT385** [comment]
I think I'm missing something here... when I make the changes as suggested above the CSS, then nothing seems to work... Do I need to append my code any differently to show the sub menu within a submenu?

My menu is shown below:

        <nav class="pushy pushy-left" data-focus="#first-link">
            <div class="pushy-content">
                <ul>
                    <li class="pushy-link"><a href="#">Home</a></li>
                    <li class="pushy-submenu">
                        <button>History & Development</button>
                        <ul>
                            <li class="pushy-link"><a href="#">ADO74</a></li>
                            <li class="pushy-link"><a href="#">Britain's best seller</a></li>
                            <li class="pushy-link"><a href="#">Building Britain's best seller</a></li>
                            <li class="pushy-link"><a href="#">Commercial ADO16</a></li>
                            <li class="pushy-link"><a href="#">History</a></li>
                    		<li class="pushy-submenu">
                            <button>International flavours</button>
                            <ul>
                            <li class="pushy-link"><a href="#">American market</a></li>
                            <li class="pushy-link"><a href="#">Australian market</a></li>
                            <li class="pushy-link"><a href="#">Chilean market</a></li>
                            <li class="pushy-link"><a href="#">Italian market</a></li>
                            <li class="pushy-link"><a href="#">Spanish market</a></li>
                            <li class="pushy-link"><a href="#">South African market</a></li>
							</ul>
							</li>
                            <li class="pushy-link"><a href="#">Makes & models</a></li>
                            <li class="pushy-link"><a href="#">Production figures</a></li>
                        </ul>
                    </li>
                    <li class="pushy-submenu">
                        <button>Cars</button>
                        <ul>
                            <li class="pushy-link"><a href="#">Item 1</a></li>
                            <li class="pushy-link"><a href="#">Item 2</a></li>
                            <li class="pushy-link"><a href="#">Item 3</a></li>
                        </ul>
                    </li>
                    <li class="pushy-submenu">
                        <button>Owning an ADO16</button>
                        <ul>
                            <li class="pushy-link"><a href="#">Item 1</a></li>
                            <li class="pushy-link"><a href="#">Item 2</a></li>
                            <li class="pushy-link"><a href="#">Item 3</a></li>
                        </ul>
                    </li>
                    <li class="pushy-submenu">
                        <button>Our Community</button>
                        <ul>
                            <li class="pushy-link"><a href="#">Item 1</a></li>
                            <li class="pushy-link"><a href="#">Item 2</a></li>
                            <li class="pushy-link"><a href="#">Item 3</a></li>
                        </ul>
                    </li>
                    <li class="pushy-submenu">
                        <button>Others</button>
                        <ul>
                            <li class="pushy-link"><a href="#">Item 1</a></li>
                            <li class="pushy-link"><a href="#">Item 2</a></li>
                            <li class="pushy-link"><a href="#">Item 3</a></li>
                        </ul>
                    </li>                    
                    <li class="pushy-link"><a href="#">Item 1</a></li>
                    <li class="pushy-link"><a href="#">Item 2</a></li>
                    <li class="pushy-link"><a href="#">Item 3</a></li>
                    <li class="pushy-link"><a href="#">Item 4</a></li>
                </ul>
            </div>
        </nav

**Comment by martianatwork** [comment]
@gerardo-rodriguez  This solution is perfect the only problem with this is that you are closing the parent when clicked on nested submenu

I have fixed this:
1. If you close a nested submenu by clicking on itself, it appears to be closing the parent submenu as well (I seems odd behavior?), It totally works fine if you are just closing the opened nested submenus by opening a closed submenu (which closes any opened nested submenus).

Proper working script: https://pastebin.com/fbzidKBS
this also now closes previous submenu/nested submenu when you open a new one

**Comment by suture** [comment]
Any progress on this?

**Pull request closed without merging**
